### ISSUE TITLE
Error comes constantly in special case

### ISSUE THREAD

**Issue by balazs-zsoldos** [everit-org/eosgi-dist-util#2]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.everit.osgi.dev.dist.util.attach.internal.reflect.ReflectUtil.callMethod(ReflectUtil.java:35)
	at org.everit.osgi.dev.dist.util.attach.internal.reflect.VirtualMachineStaticReflect.attach(VirtualMachineStaticReflect.java:56)
	at org.everit.osgi.dev.dist.util.attach.EOSGiVMManager.attachAndProcessVM(EOSGiVMManager.java:125)
	at org.everit.osgi.dev.dist.util.attach.EOSGiVMManager.refresh(EOSGiVMManager.java:330)
	at org.everit.osgi.dev.e4.plugin.EOSGiProjectManager.lambda$3(EOSGiProjectManager.java:85)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.everit.osgi.dev.dist.util.attach.internal.reflect.ReflectUtil.callMethod(ReflectUtil.java:31)
	... 5 more
    Caused by: java.io.IOException: A hozzáférés megtagadva
	at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
	at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
	at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
	at com.sun.tools.attach.spi.AttachProvider.attachVirtualMachine(AttachProvider.java:194)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	... 9 more

**Comment by balazs-zsoldos** [comment]
Fixed already
